//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18047
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nolte.IO.Vss {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nolte.IO.Vss.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AlphaVSS requires at least Windows XP. ähnelt.
        /// </summary>
        public static string AlphaVSSRequiresAtLeastWindowsXP {
            get {
                return ResourceManager.GetString("AlphaVSSRequiresAtLeastWindowsXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Another LUN resynchronization operation is already in progress. ähnelt.
        /// </summary>
        public static string AnotherLUNResynchronizationOperationIsAlreadyInProgress {
            get {
                return ResourceManager.GetString("AnotherLUNResynchronizationOperationIsAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occurred. The error code is logged in the error log file. ähnelt.
        /// </summary>
        public static string AnUnexpectedErrorOccuredTheErrorCodeIsLogg {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccuredTheErrorCodeIsLogg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unexpected error occurred during communication with writers. ähnelt.
        /// </summary>
        public static string AnUnexpectedErrorOccurredDuringCommunicationWithWriters {
            get {
                return ResourceManager.GetString("AnUnexpectedErrorOccurredDuringCommunicationWithWriters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletion of snapshot failed. See inner exception for details.  ähnelt.
        /// </summary>
        public static string DeletionOfSnapshotFailedSeeInnerExceptionF {
            get {
                return ResourceManager.GetString("DeletionOfSnapshotFailedSeeInnerExceptionF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deletion of snapshots failed ähnelt.
        /// </summary>
        public static string DeletionOfSnapshotsFailed {
            get {
                return ResourceManager.GetString("DeletionOfSnapshotsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected provider error. Check the event log for details. ähnelt.
        /// </summary>
        public static string ExpectedProviderError {
            get {
                return ResourceManager.GetString("ExpectedProviderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to detect architecture of running operating system. ähnelt.
        /// </summary>
        public static string FailedToDetectArchitectureOfRunningOperati {
            get {
                return ResourceManager.GetString("FailedToDetectArchitectureOfRunningOperati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IA64 architecture is not supported. ähnelt.
        /// </summary>
        public static string IA64ArchitectureIsNotSupported {
            get {
                return ResourceManager.GetString("IA64ArchitectureIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid XML document. Check the event log for details. ähnelt.
        /// </summary>
        public static string InvalidXMLDocumentCheckTheEventLogForDetails {
            get {
                return ResourceManager.GetString("InvalidXMLDocumentCheckTheEventLogForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum number of shadow copy storage areas has been added to the shadow copy source volume. ähnelt.
        /// </summary>
        public static string MaximumDiffAreaAssociationsReached {
            get {
                return ResourceManager.GetString("MaximumDiffAreaAssociationsReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested operation is not supported on the current operating system. ähnelt.
        /// </summary>
        public static string RequestedOperationUnsupportedByOS {
            get {
                return ResourceManager.GetString("RequestedOperationUnsupportedByOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System was unable to freeze the Distributed Transaction Coordinator (DTC) or the Kernel Transaction Manager (KTM) ähnelt.
        /// </summary>
        public static string SystemWasUnableToFreezeDtcOrKtm {
            get {
                return ResourceManager.GetString("SystemWasUnableToFreezeDtcOrKtm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The creation of a shadow copy is already in progress. ähnelt.
        /// </summary>
        public static string TheCreationOfAShadowCopyIsAlreadyInProgress {
            get {
                return ResourceManager.GetString("TheCreationOfAShadowCopyIsAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The maximum number of volumes has already been added to the shadow copy set. ähnelt.
        /// </summary>
        public static string TheMaximumNumberOfVolumesHasAlreadyBeenAddedToTheShadowCopySet {
            get {
                return ResourceManager.GetString("TheMaximumNumberOfVolumesHasAlreadyBeenAddedToTheShadowCopySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operation is not supported under the current context. ähnelt.
        /// </summary>
        public static string TheOperationIsNotSupportedUnderTheCurrentContext {
            get {
                return ResourceManager.GetString("TheOperationIsNotSupportedUnderTheCurrentContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provider encountered an error that requires the user to restart the computer. ähnelt.
        /// </summary>
        public static string TheProviderEncounteredAnErrorThatRequiresTheUserToRestartTheComputer {
            get {
                return ResourceManager.GetString("TheProviderEncounteredAnErrorThatRequiresTheUserToRestartTheComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provider returned an unexpected error code. ähnelt.
        /// </summary>
        public static string TheProviderReturnedAnUnexpectedErrorCode {
            get {
                return ResourceManager.GetString("TheProviderReturnedAnUnexpectedErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested identifier does not correspond to a registered provider. ähnelt.
        /// </summary>
        public static string TheRequestedIdentifierDoesNotCorrespondToARegisteredProvider {
            get {
                return ResourceManager.GetString("TheRequestedIdentifierDoesNotCorrespondToARegisteredProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested object does not exist. ähnelt.
        /// </summary>
        public static string TheRequestedObjectDoesNotExist {
            get {
                return ResourceManager.GetString("TheRequestedObjectDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested object was a duplicate. ähnelt.
        /// </summary>
        public static string TheRequestedObjectWasADuplicate {
            get {
                return ResourceManager.GetString("TheRequestedObjectWasADuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The system or provider has insufficient storage space. If possible delete any old or unnecessary persistent shadow copies and try again. ähnelt.
        /// </summary>
        public static string TheSystemOrProviderHasInsufficientStorageSpace {
            get {
                return ResourceManager.GetString("TheSystemOrProviderHasInsufficientStorageSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The system was unable to flush I/O writes. This can be a transient problem. It is recommended to wait ten minutes and try again, up to three times. ähnelt.
        /// </summary>
        public static string TheSystemWasUnableToFlushIOWrites {
            get {
                return ResourceManager.GetString("TheSystemWasUnableToFlushIOWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The system was unable to hold I/O writes. This can be a transient problem. It is recommended to wait ten minutes and try again, up to three times ähnelt.
        /// </summary>
        public static string TheSystemWasUnableToHoldIOWrites {
            get {
                return ResourceManager.GetString("TheSystemWasUnableToHoldIOWrites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The volume already has a revert in progress. ähnelt.
        /// </summary>
        public static string TheVolumeAlreadyHasARevertInProgress {
            get {
                return ResourceManager.GetString("TheVolumeAlreadyHasARevertInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The volume does not support the requested operation, or no provider supports it. ähnelt.
        /// </summary>
        public static string TheVolumeDoesNotSupportTheRequestedOperation {
            get {
                return ResourceManager.GetString("TheVolumeDoesNotSupportTheRequestedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The volume has already been added to the maximum number of shadow copy sets. ähnelt.
        /// </summary>
        public static string TheVolumeHasAlreadyBeenAddedToTheMaximumNumberOfShadowCopySets {
            get {
                return ResourceManager.GetString("TheVolumeHasAlreadyBeenAddedToTheMaximumNumberOfShadowCopySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The volume is not supported by the specified provider. ähnelt.
        /// </summary>
        public static string TheVolumeIsNotSupportedByTheSpecifiedProvider {
            get {
                return ResourceManager.GetString("TheVolumeIsNotSupportedByTheSpecifiedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The volume was in use and could not be locked. ähnelt.
        /// </summary>
        public static string TheVolumeWasInUseAndCouldNotBeLocked {
            get {
                return ResourceManager.GetString("TheVolumeWasInUseAndCouldNotBeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The VSS object was in an incorrect state for the requested operation. ähnelt.
        /// </summary>
        public static string TheVSSObjectWasInAnIncorrectStateForTheRequestedOperation {
            get {
                return ResourceManager.GetString("TheVSSObjectWasInAnIncorrectStateForTheRequestedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writer infrastructure is not operating properly. Check that the Event Service and VSS have been started, and check for errors associated with those services in the error log. ähnelt.
        /// </summary>
        public static string TheWriterInfrastructureIsNotOperatingProperly {
            get {
                return ResourceManager.GetString("TheWriterInfrastructureIsNotOperatingProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writer is not responding. ähnelt.
        /// </summary>
        public static string TheWriterIsNotResponding {
            get {
                return ResourceManager.GetString("TheWriterIsNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation requires {0}{1}. Detected operating system was: {2}{3}. ähnelt.
        /// </summary>
        public static string ThisOperationRequires01DetectedOperatingSystemWas23 {
            get {
                return ResourceManager.GetString("ThisOperationRequires01DetectedOperatingSystemWas23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation requires {0}{1} or later. Detected operating system was: {2}{3}. ähnelt.
        /// </summary>
        public static string ThisOperationRequires01OrLaterDetectedOperatingSystemWas23 {
            get {
                return ResourceManager.GetString("ThisOperationRequires01OrLaterDetectedOperatingSystemWas23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation requires {0}. Detected operating system was: {1}. ähnelt.
        /// </summary>
        public static string ThisOperationRequires0DetectedOperatingSystemWas1 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0DetectedOperatingSystemWas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation requires {0} or later. Detected operating system was: {1}. ähnelt.
        /// </summary>
        public static string ThisOperationRequires0OrLaterDetectedOperatingSystemWas1 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0OrLaterDetectedOperatingSystemWas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation requires {0} with at least Service Pack {1}. Detected operating system was: {2}{3}. ähnelt.
        /// </summary>
        public static string ThisOperationRequires0WithAtLeastServicePack1DetectedOperatingSystemWas23 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0WithAtLeastServicePack1DetectedOperatingSystemWas23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operation requires {0} with at least Service Pack {1}, or {2} with at least service pack {3}. Detected operating system was: {4}{5}. ähnelt.
        /// </summary>
        public static string ThisOperationRequires0WithAtLeastServicePack1Or2WithAtLeastServicePack3DetectedOperatingSystemWas45 {
            get {
                return ResourceManager.GetString("ThisOperationRequires0WithAtLeastServicePack1Or2WithAtLeastServicePack3DetectedOp" +
                        "eratingSystemWas45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This version of the hardware provider does not support this operation. ähnelt.
        /// </summary>
        public static string ThisVersionOfTheHardwareProviderDoesNotSupportThisOperation {
            get {
                return ResourceManager.GetString("ThisVersionOfTheHardwareProviderDoesNotSupportThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected system error. ähnelt.
        /// </summary>
        public static string UnexpectedSystemError {
            get {
                return ResourceManager.GetString("UnexpectedSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested method is not supported on the current operating system, or the loaded assembly is targeted for a different operating system than the one on which it is running. ähnelt.
        /// </summary>
        public static string UnsupportedOperatingSystemExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedOperatingSystemExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The MBR signature or GPT ID for one or more disks could not be set to the intended value. Check the Application event log for more information. ähnelt.
        /// </summary>
        public static string VssCannotRevertDiskIdExceptionMessage {
            get {
                return ResourceManager.GetString("VssCannotRevertDiskIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The shadow copy contains only a subset of the volumes needed by the writer to correctly back up the application component. ähnelt.
        /// </summary>
        public static string VssInconsistentSnapshotWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssInconsistentSnapshotWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writer operation failed because of an error that might recur if another shadow copy is created. ähnelt.
        /// </summary>
        public static string VssNonRetryableWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssNonRetryableWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writer ran out of memory or other system resources. ähnelt.
        /// </summary>
        public static string VssOutOfResourcesExceptionMessage {
            get {
                return ResourceManager.GetString("VssOutOfResourcesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writer is reporting one or more component-level errors. ähnelt.
        /// </summary>
        public static string VssPartialFailureWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssPartialFailureWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writer failed due to an error that would likely not occur if the entire backup, restore, or shadow copy creation process was restarted ähnelt.
        /// </summary>
        public static string VssRetryableWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssRetryableWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The specified snapshot specifies a shadow copy that does not exist in the Backup Components Document. ähnelt.
        /// </summary>
        public static string VssSnapshotNotInSetExceptionMessage {
            get {
                return ResourceManager.GetString("VssSnapshotNotInSetExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The writer operation failed because of a time-out between the Freeze and Thaw events. ähnelt.
        /// </summary>
        public static string VssTimeoutWriterExceptionMessage {
            get {
                return ResourceManager.GetString("VssTimeoutWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resynchronization destination contained a volume that was not explicitly included. ähnelt.
        /// </summary>
        public static string VssUnselectedVolumeExceptionMessage {
            get {
                return ResourceManager.GetString("VssUnselectedVolumeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Writer status is not available for one or more writers. A writer may have reached the maximum number of available backup and restore sessions. ähnelt.
        /// </summary>
        public static string VssWriterStatusNotAvailableExceptionMessage {
            get {
                return ResourceManager.GetString("VssWriterStatusNotAvailableExceptionMessage", resourceCulture);
            }
        }
    }
}
